### ISSUE TITLE
[Architecture] How we develop a reusable and compositional module?

### ISSUE THREAD

**Issue by fanny** [heydevoss/heydev#2]
## The Reusable Architecture

*Coming Soon*

## Inspirations
[ant-design](https://ant.design/docs/react/introduce)
[storybook](https://storybook.js.org/)

**Comment by vinifarias** [comment]
To start the discussion I recommend the [article](https://hackernoon.com/the-three-types-of-reusable-react-components-37a6bf7c2d69). The author explains the types of reusable react components, it's important to us to know it.
